# Generated by Django 4.2.7 on 2026-02-28 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('campus', 'Campus'), ('national', 'National'), ('hotline', 'Hotline'), ('online', 'Online')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('availability', models.CharField(default='24/7', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
