# Generated by Django 4.2.7 on 2026-02-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mood_tracking', '0001_initial'),
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionprompt',
            name='mood_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='mood_tracking.moodentry'),
        ),
    ]
