# Generated by Django 5.0.1 on 2026-03-05 01:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='space_analyses/%Y/%m/')),
                ('mime_type', models.CharField(max_length=50)),
                ('lighting_quality', models.CharField(choices=[('poor', 'Poor'), ('moderate', 'Moderate'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20)),
                ('lighting_type', models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial'), ('mixed', 'Mixed'), ('dim', 'Dim')], max_length=20)),
                ('clutter_level', models.CharField(choices=[('minimal', 'Minimal'), ('moderate', 'Moderate'), ('cluttered', 'Cluttered')], max_length=20)),
                ('calming_elements', models.JSONField(help_text='List of calming elements (plants, soft colors, natural materials, artwork)')),
                ('relaxation_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('environment_tips', models.JSONField(help_text='List of actionable environment improvement tips')),
                ('personalized_comment', models.TextField()),
                ('interaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Space Analysis',
                'verbose_name_plural': 'Space Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='voice_analyses/%Y/%m/')),
                ('audio_duration_seconds', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=50)),
                ('energy_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('detected_emotions', models.JSONField(help_text='List of detected emotions (happy, sad, anxious, calm, stressed, energetic, fatigued, neutral)')),
                ('fatigue_indicator', models.BooleanField()),
                ('speech_pace', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], max_length=10)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('supportive_message', models.TextField()),
                ('interaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voice Analysis',
                'verbose_name_plural': 'Voice Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('entries_analyzed', models.PositiveIntegerField()),
                ('average_mood', models.FloatField()),
                ('mood_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20)),
                ('dominant_emotions', models.JSONField(help_text='List of top 3 dominant emotions for the week')),
                ('energy_pattern', models.TextField(help_text='Natural language description of energy patterns')),
                ('peak_days', models.JSONField(help_text='List of day names when mood scores were highest')),
                ('low_days', models.JSONField(help_text='List of day names requiring attention')),
                ('weekly_summary', models.TextField(help_text='Natural language weekly summary')),
                ('focus_areas', models.JSONField(help_text='List of focus areas for improvement')),
                ('achievements', models.JSONField(help_text='List of positive achievements from the week')),
                ('chart_data', models.JSONField(help_text='Formatted data for frontend chart components')),
                ('interaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weekly Insights',
                'verbose_name_plural': 'Weekly Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='crisis_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='detected_mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='follow_up_questions',
            field=models.JSONField(blank=True, help_text='List of follow-up questions to encourage engagement', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='interaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='resource_suggestions',
            field=models.JSONField(blank=True, help_text='List of resource suggestions relevant to conversation', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='suggested_activities',
            field=models.JSONField(blank=True, help_text='List of suggested activities based on detected mood', null=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_service.conversation'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='ai_service__convers_6bba03_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-timestamp'], name='ai_service__user_id_72f8cf_idx'),
        ),
        migrations.AddField(
            model_name='spaceanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyinsights',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='spaceanalysis',
            index=models.Index(fields=['user', '-created_at'], name='ai_service__user_id_184e00_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceanalysis',
            index=models.Index(fields=['user', '-created_at'], name='ai_service__user_id_3ddd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyinsights',
            index=models.Index(fields=['user', '-created_at'], name='ai_service__user_id_57e390_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyinsights',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='ai_service__user_id_d44991_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyinsights',
            constraint=models.UniqueConstraint(fields=('user', 'period_start', 'period_end'), name='unique_user_weekly_period'),
        ),
    ]
