# Generated by Django 5.0.1 on 2026-03-10 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0004_spaceanalysis_voiceanalysis_weeklyinsights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyinsights',
            name='evidence',
            field=models.JSONField(default=list, help_text='Supporting evidence linking insights to source data'),
        ),
        migrations.AddField(
            model_name='weeklyinsights',
            name='overall_confidence',
            field=models.FloatField(default=0.85, help_text='Overall confidence score for the analysis (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
