# Generated by Django 4.2.7 on 2026-03-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moodconversationlink',
            new_name='chat_bridge_mood_en_10541d_idx',
            old_name='chat_bridge_mood_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='moodconversationlink',
            new_name='chat_bridge_convers_af63e7_idx',
            old_name='chat_bridge_conversation_idx',
        ),
        migrations.RenameIndex(
            model_name='moodconversationlink',
            new_name='chat_bridge_generat_1e183b_idx',
            old_name='chat_bridge_status_idx',
        ),
    ]
