# Generated by Django 4.2.7 on 2026-03-15 10:49

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, max_length=500)),
        ),
    ]
