# Generated by Django 4.2.7 on 2026-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracking', '0003_alter_moodentry_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='sound_note',
            field=models.FileField(blank=True, null=True, upload_to='mood_audio/'),
        ),
    ]
